# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Scrapbook
email: angusbayley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Scrapbook is a London-based septet playing the music of Angus Bayley.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://scrapbook-music.com" # the base hostname & protocol for your site
twitter_username: angusbayley
#facebook_username: scrapbook-band

# Build settings
markdown: kramdown
